project_id = "icheon-savepoint"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[auth]
enabled = true
site_url = "http://127.0.0.1:3002"
additional_redirect_urls = [
  "http://127.0.0.1:3000/auth/callback",
  "http://127.0.0.1:3002/auth/callback",
]

[auth.external.kakao]
enabled = true
client_id = "env(SUPABASE_AUTH_EXTERNAL_KAKAO_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_KAKAO_SECRET)"
email_optional = true

[studio]
enabled = true
port = 54323
